FORMAT: 1A
HOST: https://api-staging.aoms-np.dealshield.com/

# Assurance Order Management System (AOMS)

AOMS is a system to accept orders for Assurance Protection
products, such as Repair Guarantee and eventually PSI and DealShield.

## Orders [/orders/assurance]

### Create a New Order [POST]

You may create your own order using this action. It takes a JSON
object containing physical location name, order account number (seller
number), productId, and other vehicle-related information.

+ Request (application/json)
    + Attributes (Order Create Payload)
        
    + Body

            {
                "physicalLocation": {
                    "name": "MISS"
                },
                "orderingAccountNumber": 5123456,
                "productId": "repairGuarantee",
                "vehicle": {
                    "mmr": 24000,
                    "vin": "JF2SJADC3FH504814",
                    "year": 2015,
                    "make": "SUBARU",
                    "trim": "Premium Moonroof",
                    "model": "Forester",
                    "odometer": 12345
                }
            }

+ Response 201 (application/json)

    + Headers

            Location: https://api-staging.aoms-np.dealshield.com/orders/assurance/id/rg_fe880faf-7d44-4b7d-8245-2f12bdbb4011

    + Body

            {
                "href": "https://api-staging.aoms-np.dealshield.com/orders/assurance/id/rg_fe880faf-7d44-4b7d-8245-2f12bdbb4011",
                "orderingAccountNumber": 5123456,
                "status": "PENDING",
                "productId": "repairGuarantee",
                "vehicle": {
                    "mmr": 24000,
                    "currency": "USD",
                    "vin": "JF2SJADC3FH504814",
                    "year": 2015,
                    "make": "SUBARU",
                    "trim": "Premium Moonroof",
                    "model": "Forester",
                    "odometer": 12345,
                    "odometerUnit": "miles"
                },
                "physicalLocation": {
                    "name": "MISS",
                    "operationLocation": {
                        "href": "https://integration1.api.manheim.com/locations/id/MISS"
                    },
                    "type": "AT_AUCTION"
                },
                "sellerAccount": 5123456,
                "unit": {
                    "href": "https://api.manheim.com/XXXXX"
                },
                "createdOn": "2015-08-05T08:40:51.620Z"
            }

### Order [/orders/assurance/id/{id}]

### Retrieve an Order [GET]
Get the order object by providing an id

+ Parameters
    + id: `rg_fe880faf-7d44-4b7d-8245-2f12bdbb4011` (required)

+ Response 200 (application/json)
    + Attributes (Order)
    
### Create more than one order  [POST /orders/assurance/bulk]

+ Request (application/json)
    + Attributes (array[Order Create Payload])
    
    + Body
    ```
        [
            {
                "physicalLocation": {
                    "name": "AAAA",
                    "type": "AT_AUCTION"
                },
                "orderingAccountNumber": 5123456,
                "productId": "repairGuarantee",
                "vehicle": {
                    "mmr": 24000,
                    "vin": "JF2SJADC3FH504814",
                    "year": 2015,
                    "make": "SUBARU",
                    "trim": "Premium Moonroof",
                    "model": "Forester",
                    "odometer": 12345
                }
            }
        ]
    ```
        
+ Response 201 (application/json)
    + Attributes
        + href
        + count (number): number of items
        + items (array[Order])

### Retrieve multiple orders using seller number and vin combination [POST /orders/assurance/search]

Get more than one order by posting a body which contains an array of objects

+ Request (application/json)
    + Attributes (array[Order Search Payload])
    
    + Body
    ```
        [
            { vin: 'JF2SJADC3FH504814', orderingAccountNumber: 5123456, productId: 'repairGuarantee' }
        ]
    ```
        
+ Response 200 (application/json)
    + Attributes
        + href
        + count `1` (number)
            number of items
        + items (array[Order])
        

# Data Structures

## Order (object)
+ physicalLocation
    + name `AAAA`
        the name of the location
    + type (enum, required)
        type of location
        + Default: AT_AUCTION
        + Members
            + AT_AUCTION
            + AT_DEALERSHIP
    + operationLocation
        + href `https://api.manheim.com/locations/id/AAAA`
            URL of details about the physical location
    + address `6325 Peachtree Dunwoody Road`
    + city `Atlanta`
    + state `GA`
    + zip `30328`
+ orderingAccountNumber (number, required)
    (Manheim) account number (5 million number) of the ordering entity.
    This is the account that will be billed for the product
+ sellerAccount: Manheim account number of the seller
+ buyerAccount: Manheim account number of the buyer
+ productId (enum, required)
    the product id
    + Members
        + repairGuarantee
+ status (enum)
    the order state
    + Members
        + PENDING
        + CANCELLED
        + FULFILLED
+ reasonForCancellation: the reason order state is cancelled
+ vehicle (Vehicle, required)
    vehicle information
+ createdOn: timestamp of when order was created (string) - Timestamp
+ updatedOn: timestamp of when order was updated (string) - Timestamp

## Vehicle (object)
+ vin: Vehicle Identification Number (required)
+ year (number, required)
+ make (required)
+ trim (required)
+ model (required)
+ salePrice (number)
    the price of the vehicle
+ mmr (number): MMR of the vehicle
+ currency
    the currency for the the vehicle price
    + Default: USD
+ odometer (number, required)
    the number of miles/kilometers traveled
+ odometerUnit (enum)
    the measuring unit for the odometer
    + Default: miles
    + Members
        + miles
        + kilometers
+ specialAttributes (array[enum])
    tags that can apply to a vehicle
    + Members
        + electricVehicle
        + hybridVehicle
        + redLightVehicle
        + salvage
        
## Order Create Payload (object)
+ physicalLocation
    + name `AAAA`
        the name of the location
    + type (enum, required)
        type of location
        + Members
            + AT_AUCTION
            + AT_DEALERSHIP
    + operationLocation
        + href `https://api.manheim.com/locations/id/AAAA`
            URL of details about the physical location
    + address `6325 Peachtree Dunwoody Road`
    + city `Atlanta`
    + state `GA`
    + zip `30319`
+ orderingAccountNumber (number, required)
    (Manheim) account number (5 million number) of the ordering entity.
    This is the account that will be billed for the product
+ productId (enum, required)
    the product id
    + Members
        + repairGuarantee
+ vehicle (Vehicle)

## Order Search Payload (object)
+ vin (required): Vehicle Identification Number
+ orderingAccountNumber (number, required): the 5 million number of the person placing the order
+ productId (enum, required)
    the product id
    + Members
        + repairGuarantee