FORMAT: 1A
HOST: https://api.dealshield.com/

# Assurance Order Management System (AOMS)

AOMS is a system to accept orders for Assurance Protection
products, such as Repair Guarantee and eventually PSI and DealShield.

## Orders [/orders/assurance]

### Create a New Order [POST]

You may create your own order using this action. It takes a JSON
object containing physical location name, order account number (seller
number), productId, and other vehicle-related information.

+ Request (application/json)
    + Attributes
        + physicalLocation
            + name (required)
                the name of the auction
        + orderingAccountNumber (number, required)
            (Manheim) account number (5 million number) of the ordering entity.
            This is the account that will be billed for the product
        + productId (enum, required)
            the product id
            + Members
                + REPAIR_GUARANTEE
        + vehicle (Vehicle, required)
        
    + Body

            {
                "physicalLocation": {
                    "name": "AAAA"
                },
                "orderingAccountNumber": 5123456,
                "productId": "REPAIR_GUARANTEE",
                "vehicle": {
                    "mmr": 24000,
                    "vin": "JF2SJADC3FH504814",
                    "year": 2015,
                    "make": "SUBARU",
                    "trim": "Premium Moonroof",
                    "model": "Forester",
                    "odometer": 12345
                }
            }

+ Response 201 (application/json)

    + Headers

            Location: https://api.dealshield.com/orders/assurance/id/rg_fe880faf-7d44-4b7d-8245-2f12bdbb4011

    + Body

            {
                "href": "https://api.dealshield.com/orders/assurance/id/rg_fe880faf-7d44-4b7d-8245-2f12bdbb4011",
                "orderingAccountNumber": 5123456,
                "status": "PENDING",
                "productId": "REPAIR_GUARANTEE",
                "vehicle": {
                    "mmr": 24000,
                    "currency": "USD",
                    "vin": "JF2SJADC3FH504814",
                    "year": 2015,
                    "make": "SUBARU",
                    "trim": "Premium Moonroof",
                    "model": "Forester",
                    "odometer": 12345,
                    "odometerType": 'miles'
                },
                "createdOn": "2015-08-05T08:40:51.620Z"
            }

### Order [/orders/assurance/id/{id}]

### Retrieve an Order [GET]

+ Parameters
    + id: `rg_fe880faf-7d44-4b7d-8245-2f12bdbb4011` (required)

Get the order object by providing an id

+ Response 200 (application/json)
    + Attributes (Order)
    

### Retrieve multiple orders using seller number and vin combination [POST /orders/assurance]

Get more than one order by posting a body which contains an array of
objects

+ Request (application/json)
    + Attributes (array[Order Search Payload])
    
    + Body
        [
            { vin: 'JF2SJADC3FH504814', orderingAccountNumber: 5123456 }
        ]

# Data Structures
## Order (object)
+ physicalLocation
    + name: `AAAA` the name of the auction (required)
+ orderingAccountNumber: the 5 million number of the person placing the order (number, required)
+ product (enum, required)
    the product id
    + Members
        + REPAIR_GUARANTEE
+ vehicle: vehicle information (Vehicle, required)
+ createdOn: timestamp of when order was created (string) - Timestamp

## Vehicle (object)
+ vin: Vehicle Identification Number (required)
+ year: Vehicle year (number, required)
+ make: Vehicle make (required)
+ trim: Vehicle trim (required)
+ model: Vehicle model (required)
+ salePrice: the price of the vehicle (number)
+ mmr: MMR of the vehicle (number)
+ currency
    the currency for the the vehicle price
    + Default: USD
+ odometer: the number of miles/kilometers traveled (number, required)
+ odometerType (enum)
    the measuring unit for the odometer
    + Default: miles
    + Members
        + miles
        + kilometer

## Order Search Payload (object)
+ vin: Vehicle Identification Number (required)
+ orderingAccountNumber: the 5 million number of the person placing the order (number, required)